/**
 * Web Worker script for barcode scanning using ZBar library
 * Imports required ZBar dependencies and sets up message handling
 */

importScripts("zbar.js"); // glue JS code, generated by emscripten (together with zbar.wasm)
importScripts("koder-zbar.js"); // user-friendly API

/**
 * Self-executing async function to initialize scanner and set up message handler
 */
(async () => {
  // Initialize Koder
  const koder = await new KoderZbar().initialize({wasmDirectory: "./"});

  /**
   * Handles incoming messages containing image data to scan
   * @param {MessageEvent} event - Message event containing image data
   * @param {Object} event.data - Message payload
   * @param {number} event.data.width - Image width
   * @param {number} event.data.height - Image height
   * @param {Uint8Array} event.data.data - Raw image data buffer
   */
  self.addEventListener('message', event => {
    // Set image dimensions if provided
    if ('width' in event.data && 'height' in event.data) {
      this.width = event.data.width;
      this.height = event.data.height;
    }

    const {data} = event.data;
    if (!data) return;

    // Track scan performance
    const t0 = new Date().getTime();
    const scanResult = koder.decode(data, this.width, this.height);
    const t1 = new Date().getTime();

    // Post scan results back to main thread if successful
    if (scanResult) {
      console.log(`Zbar: Scanned in ${t1-t0} ms`);
      postMessage({
        data: scanResult.code, // Decoded barcode data
        type: scanResult.type, // Type of barcode detected
        ms: t1-t0 // Scan duration in milliseconds
      });
    }
  });
})();